name: Upload to ElasticBeanstalk

on:
  push:
    paths:
    - 'version.properties'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test
      run: ./gradlew test -Pusername=JFL110 -Ppassword=${{ secrets.GP_PUBLISH_TOKEN }}
    - name: Produce Zip
      run: ./gradlew ebZip -Pusername=JFL110 -Ppassword=${{ secrets.GP_PUBLISH_TOKEN }}
    - name: Upload to Test Env
       uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ID }}
        aws_secret_key: ${{ secrets.AWS_KEY }}
        application_name: spring-websockets-example-2
        environment_name: SpringWebsocketsExample2-env
        version_label: ${{ steps.buildnumber.outputs.build_number }}
        region: eu-west-2
        deployment_package: ./build/spring-websockets-eb-bundle.zip
